#ifndef SWAY_GAPI_GL_HPP
#define SWAY_GAPI_GL_HPP

#include <sway/gapi/gl/oglblendequationconvertor.hpp>
#include <sway/gapi/gl/oglblendfunctionconvertor.hpp>
#include <sway/gapi/gl/oglblendstate.hpp>
#include <sway/gapi/gl/oglbufferidgenerator.hpp>
#include <sway/gapi/gl/oglbuffertargetconvertor.hpp>
#include <sway/gapi/gl/oglcapability.hpp>
#include <sway/gapi/gl/oglclearflagconvertor.hpp>
#include <sway/gapi/gl/oglcomparefunctionconvertor.hpp>
#include <sway/gapi/gl/oglcullfaceconvertor.hpp>
#include <sway/gapi/gl/ogldepthstate.hpp>
#include <sway/gapi/gl/ogldrawcall.hpp>
#include <sway/gapi/gl/oglframebuffer.hpp>
#include <sway/gapi/gl/oglfrontfaceconvertor.hpp>
#include <sway/gapi/gl/oglgenericbuffer.hpp>
#include <sway/gapi/gl/oglgenericshader.hpp>
#include <sway/gapi/gl/oglgenericshadertypeconvertor.hpp>
#include <sway/gapi/gl/oglpixelformatconvertor.hpp>
#include <sway/gapi/gl/oglpixelstoragemodeconvertor.hpp>
#include <sway/gapi/gl/oglrasterizerstate.hpp>
#include <sway/gapi/gl/oglrenderbuffer.hpp>
#include <sway/gapi/gl/oglshaderexceptions.hpp>
#include <sway/gapi/gl/oglshaderpreprocessor.hpp>
#include <sway/gapi/gl/oglshaderprogram.hpp>
#include <sway/gapi/gl/oglstatecapabilityconvertor.hpp>
#include <sway/gapi/gl/oglstatecontext.hpp>
#include <sway/gapi/gl/oglstateenabledable.hpp>
#include <sway/gapi/gl/oglstenciloperationconvertor.hpp>
#include <sway/gapi/gl/oglstencilstate.hpp>
#include <sway/gapi/gl/ogltexture.hpp>
#include <sway/gapi/gl/ogltextureidgenerator.hpp>
#include <sway/gapi/gl/ogltexturesampler.hpp>
#include <sway/gapi/gl/ogltexturetargetconvertor.hpp>
#include <sway/gapi/gl/ogluniform.hpp>
#include <sway/gapi/gl/oglvertexarray.hpp>
#include <sway/gapi/gl/oglvertexattriblayout.hpp>
#include <sway/gapi/gl/oglviewport.hpp>
#include <sway/gapi/gl/typeutils.hpp>
#include <sway/gapi/glmacros.hpp>

#endif  // SWAY_GAPI_GL_HPP
